# Generated by Django 4.2.4 on 2023-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsearch', '0005_alter_searchresults_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresults',
            name='thumbnail_url',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
